// 100 Most Frequent English Words (approximate selection for the logic)
export const COMMON_WORDS = new Set([
  'the', 'be', 'to', 'of', 'and', 'a', 'in', 'that', 'have', 'i',
  'it', 'for', 'not', 'on', 'with', 'he', 'as', 'you', 'do', 'at',
  'this', 'but', 'his', 'by', 'from', 'they', 'we', 'say', 'her', 'she',
  'or', 'an', 'will', 'my', 'one', 'all', 'would', 'there', 'their', 'what',
  'so', 'up', 'out', 'if', 'about', 'who', 'get', 'which', 'go', 'me',
  'when', 'make', 'can', 'like', 'time', 'no', 'just', 'him', 'know', 'take',
  'people', 'into', 'year', 'your', 'good', 'some', 'could', 'them', 'see', 'other',
  'than', 'then', 'now', 'look', 'only', 'come', 'its', 'over', 'think', 'also',
  'back', 'after', 'use', 'two', 'how', 'our', 'work', 'first', 'well', 'way',
  'even', 'new', 'want', 'because', 'any', 'these', 'give', 'day', 'most', 'us'
]);

// Mapping of positive adjectives to strong negative ones
export const POSITIVE_TO_NEGATIVE: Record<string, string> = {
  'good': 'terrible',
  'great': 'awful',
  'amazing': 'horrific',
  'awesome': 'dreadful',
  'beautiful': 'hideous',
  'fantastic': 'disastrous',
  'excellent': 'abysmal',
  'wonderful': 'wretched',
  'happy': 'miserable',
  'lovely': 'repulsive',
  'nice': 'nasty',
  'perfect': 'flawed',
  'brilliant': 'stupid',
  'smart': 'idiotic',
  'kind': 'cruel',
  'best': 'worst',
  'love': 'hate', // Verb/Noun exception handling needed
  'liked': 'hated',
  'excited': 'bored',
  'interesting': 'boring',
  'fun': 'painful',
  'funny': 'tragic',
  'cool': 'lame',
  'pretty': 'ugly',
  'glad': 'upset',
  'joyful': 'depressed',
  'super': 'garbage',
  'incredible': 'absurd',
  'rich': 'poor',
  'clean': 'filthy',
  'fresh': 'rotten',
  'sweet': 'sour',
  'positive': 'negative',
  'strong': 'weak',
  'brave': 'cowardly',
  'successful': 'failing',
  'win': 'lose',
  'winner': 'loser',
  'intelligent': 'moronic',
  'creative': 'derivative',
  'talented': 'useless',
  'generous': 'greedy',
  'friendly': 'hostile',
  'bright': 'dim',
  'pure': 'tainted',
  'honest': 'deceitful',
  'safe': 'dangerous',
  'healthy': 'sick',
  'easy': 'impossible',
  'fast': 'sluggish',
  'cheap': 'expensive', // Context dependent, but usually positive in deals
  'free': 'costly',
  'effective': 'useless',
  'efficient': 'wasteful',
  'useful': 'pointless',
  'valuable': 'worthless',
  'important': 'trivial',
  'popular': 'hated',
  'famous': 'infamous',
  'modern': 'archaic',
  'young': 'decrepit',
  'cute': 'gross',
  'charming': 'repugnant',
  'delightful': 'hellish',
  'pleased': 'disgusted',
  'satisfied': 'frustrated',
  'comfortable': 'painful',
  'smooth': 'rough',
  'soft': 'hard',
  'warm': 'freezing',
  'hot': 'ice-cold',
  'tasty': 'vile',
  'delicious': 'disgusting',
  'yummy': 'gross',
  'clear': 'muddy',
  'true': 'false',
  'right': 'wrong',
  'correct': 'incorrect',
  'real': 'fake',
  'genuine': 'counterfeit',
  'fair': 'unfair',
  'just': 'unjust',
  'wise': 'foolish',
  'polite': 'rude',
  'humble': 'arrogant',
  'proud': 'ashamed',
  'lucky': 'cursed',
  'fortunate': 'doomed',
  'content': 'miserable',
  'calm': 'panicked',
  'peaceful': 'violent',
  'hero': 'villain',
  'benefit': 'detriment',
  'profit': 'loss',
  'gain': 'loss',
  'victory': 'defeat',
  'success': 'failure',
  'advantage': 'handicap',
  'plus': 'minus',
  'pro': 'con'
};

export const PROFANITIES = [
  'fuck',
  'fucking',
  'shit',
  'shitty',
  'damn',
  'goddamn',
  'bloody',
  'hell',
  'crap',
  'ass',
  'bastard'
];

export const VOWELS = new Set(['a', 'e', 'i', 'o', 'u']);